//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoServices.LichVanNien {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LichVanNien.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name lichvansuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lichvansu", ReplyAction="*")]
        LichVanNien.lichvansuResponse lichvansu(LichVanNien.lichvansuRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lichvansuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lichvansu", Namespace="http://tempuri.org/", Order=0)]
        public LichVanNien.lichvansuRequestBody Body;
        
        public lichvansuRequest() {
        }
        
        public lichvansuRequest(LichVanNien.lichvansuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lichvansuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int iYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int iMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int iDay;
        
        public lichvansuRequestBody() {
        }
        
        public lichvansuRequestBody(int iYear, int iMonth, int iDay) {
            this.iYear = iYear;
            this.iMonth = iMonth;
            this.iDay = iDay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lichvansuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lichvansuResponse", Namespace="http://tempuri.org/", Order=0)]
        public LichVanNien.lichvansuResponseBody Body;
        
        public lichvansuResponse() {
        }
        
        public lichvansuResponse(LichVanNien.lichvansuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lichvansuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement lichvansuResult;
        
        public lichvansuResponseBody() {
        }
        
        public lichvansuResponseBody(System.Xml.Linq.XElement lichvansuResult) {
            this.lichvansuResult = lichvansuResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : LichVanNien.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<LichVanNien.Service1Soap>, LichVanNien.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LichVanNien.lichvansuResponse LichVanNien.Service1Soap.lichvansu(LichVanNien.lichvansuRequest request) {
            return base.Channel.lichvansu(request);
        }
        
        public System.Xml.Linq.XElement lichvansu(int iYear, int iMonth, int iDay) {
            LichVanNien.lichvansuRequest inValue = new LichVanNien.lichvansuRequest();
            inValue.Body = new LichVanNien.lichvansuRequestBody();
            inValue.Body.iYear = iYear;
            inValue.Body.iMonth = iMonth;
            inValue.Body.iDay = iDay;
            LichVanNien.lichvansuResponse retVal = ((LichVanNien.Service1Soap)(this)).lichvansu(inValue);
            return retVal.Body.lichvansuResult;
        }
    }
}
